app:
  docker:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'nginx:latest'
  type: docker
info:
  description: kelvin-nginx-tutorial
  name: kelvin-nginx-tutorial
  title: kelvin-nginx-tutorial
  version: 1.0.0
spec_version: 1.0.0
system:
  ports:
    - type: host
      name: http-port
      host:
        port: 80
  volumes:
    - name: static-page
      target: /usr/share/nginx/html/index.html
      type: text
      text:
        base64: true
        encoding: utf-8
        data: >-
          PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8aGVhZD4KCTxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KCTxtZXRhIGh0dHAtZXF1aXY9IlgtVUEtQ29tcGF0aWJsZSIgY29udGVudD0iSUU9ZWRnZSI+Cgk8dGl0bGU+S0lDUyBwbGF0Zm9ybTwvdGl0bGU+Cgk8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9IiI+Cgk8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJCWJvZHkgewoJCQltYXJnaW46IDIwcHg7CgkJCXBhZGRpbmc6IDBweDsKCQkJZm9udC1mYW1pbHk6IEhlbHZldGljYSwgQXJpYWw7CgkJCWJhY2tncm91bmQtY29sb3I6ICNEREQ7CgkJCWNvbG9yOiAjNDQ0OwoJCQlmb250LXNpemU6IDEuNWVtOwoJCQlsaW5lLWhlaWdodDogMS41OwoJCX0KCTwvc3R5bGU+CjwvaGVhZD4KPGJvZHk+Cgk8ZGl2IHN0eWxlPSJ0ZXh0LWFsaWduOiBjZW50ZXI7Ij4KCQk8c3ZnPgoJCQk8dXNlIF9uZ2NvbnRlbnQtcWJmLWM4Mz0iIiB4bGluazpocmVmPSIjcGstbG9nby1rZWx2aW4iPgoJCQkJPHN5bWJvbCBpZD0icGstbG9nby1rZWx2aW4iIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDQwIDQwIj4KCQkJCQk8ZyBjb2xvcj0iIzM2NjU2ZCI+CgkJCQkJCTxwYXRoIGZpbGw9ImN1cnJlbnRjb2xvciIgZD0iTTIwIDEuNjY3QzkuOTE3IDEuNjY3IDEuNjY3IDkuOTE3IDEuNjY3IDIwYzAgMTAuMDgzIDguMjUgMTguMzMzIDE4LjMzMyAxOC4zMzMgMTAuMDgzIDAgMTguMzMzLTguMjUgMTguMzMzLTE4LjMzMyAwLTEwLjA4My04LjI1LTE4LjMzMy0xOC4zMzMtMTguMzMzem0wIDM1LjUyQzEwLjQ5IDM3LjE4OCAyLjgxMiAyOS41MSAyLjgxMiAyMCAyLjgxMyAxMC40OSAxMC40OSAyLjgxMiAyMCAyLjgxMmM5LjUxIDAgMTcuMTg4IDcuNjc4IDE3LjE4OCAxNy4xODggMCA5LjUxLTcuNjc4IDE3LjE4OC0xNy4xODggMTcuMTg4eiI+PC9wYXRoPgoJCQkJCQk8cGF0aCBmaWxsPSJjdXJyZW50Y29sb3IiIGQ9Ik0yOC43MDggMjkuMTY3bC05LjYyNS05Ljc0IDkuMTY3LTguNTk0aC0xLjYwNGwtOC45MzggOC4yNVYxMC43MmgtMS4xNDVWMjkuMjhoMS4xNDV2LTkuNjI1bDkuMzk2IDkuNTF6Ij48L3BhdGg+CgkJCQkJCTxjaXJjbGUgZmlsbD0iY3VycmVudGNvbG9yIiBjeD0iMTEuNzUiIGN5PSIxMS4wNjMiIHI9IjEiPjwvY2lyY2xlPgoJCQkJCTwvZz4KCQkJCTwvc3ltYm9sPgoJCQk8L3VzZT4KCQk8L3N2Zz4KCTwvZGl2PgoJPGRpdiBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyBjb2xvcjogIzM2NjU2ZCI+CgkJPGgyPgoJCQlXZWxjb21lIHRvIHRoZSBLSUNTIHBsYXRmb3JtCgkJPC9oMj4KCTwvZGl2PgoJPGRpdiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgbWF4LXdpZHRoOiAxMjgwcHg7IG1hcmdpbjogMCBhdXRvOyI+CgkJVGhlIEtJQ1MgUGxhdGZvcm0gZW5hYmxlcyBhcHBsaWNhdGlvbiBjcmVhdGlvbiBhbmQgbWFuYWdlbWVudCwgYWxvbmcgd2l0aCBkZXZpY2UgbWFuYWdlbWVudCBhbmQgb3JjaGVzdHJhdGlvbiwgdG8gYXVnbWVudCBsZWdhY3kgY29udHJvbCBzeXN0ZW1zIHdpdGggbW9kZXJuIHJlYWwtdGltZSBvcHRpbWl6YXRpb24gYW5kIGNvbnRyb2wuIEtlbHZpbiBhcHBzIGNhbiBhbHNvIHN0cmVhbSB2YWx1YWJsZSBtZXRyaWNzIGFuZCBhZ2dyZWdhdGVzIGJhY2sgdG8gdGhlIHRpbWUtc2VyaWVzIERhdGEgQmFzZSBmb3IgZnVydGhlciBhbmFseXRpY3MgYW5kIGluc2lnaHQuCgk8L2Rpdj4KPC9ib2R5Pgo8L2h0bWw+Cgo=
  privileged: false
